"""Add unique to email

Revision ID: 569cce64c1bf
Revises: 54efcb45c014
Create Date: 2022-12-04 21:02:03.406001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569cce64c1bf'
down_revision = '54efcb45c014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
